### ISSUE TITLE
Request: Ability to change checkboxes in AJAX content

### ISSUE THREAD

**Issue by FiZiX** [dciccale/Custom-radio-checkbox#1]
Perhaps there's already a way to do this but I didn't see one: It would be nice if there was a function that could be called after content is loaded via AJAX to convert the checkboxes in the AJAX content.

**Comment by dciccale** [comment]
For now there is no way to do it, for the next version i will add a function to call whenever you want and also allow passing a context selector where the checkboxes or radio are contained.

thanks!

**Comment by dciccale** [comment]
Done!

Now if you call $("selector").customRadioCheckbox(); it will customize every radio or checkbox inside that element.

I have added an example of ajax loaded content to help on the usage.

**Comment by FiZiX** [comment]
Wow, that was incredibly fast. Thanks!
