### ISSUE TITLE
Not working on touch devices

### ISSUE THREAD

**Issue by jordan-sowers** [dciccale/Custom-radio-checkbox#10]
Currently using Custom-radio-checkbox and everything works, except on touch devices. The class changes on touch, so it appears the checkbox has been checked, but it doesn't. It only changes the appearance, not the hidden input's state.

**Comment by dciccale** [comment]
I've tried it in a sony xperia z and it works fine (since i'm using chrome). on what mobile device are you trying this? which browser?

**Comment by dciccale** [comment]
it may be a wierd bug, because in the script I only apply the class when the change event is fired (meaning it was checked/unchecked)

please specify where are you testing

**Comment by dciccale** [comment]
Close due to no response.
