### ISSUE TITLE
Not getting updated when using prop

### ISSUE THREAD

**Issue by rrrnld** [dciccale/Custom-radio-checkbox#11]
When setting `$('.foo').prop('checked', false)` the checked class does not automatically get removed from the `<i>`-element. At the moment you have to do a workaround like this: 

``` js
jQuery('input[type=checkbox]')
    .prop('checked', false)
    .next()
    .removeClass('checkbox-checked');
```

**Comment by dciccale** [comment]
this plugin is ment to be unobtrusive, since the jquery .prop() method doesn't fire the native DOM change event on the input, the class won't be updated.

you could do this instead

``` javascript
jQuery('input[type=checkbox]')
    .prop('checked', false)
    .change();
```

or better yet, use the plugin namespace event

``` javascript
jQuery('input[type=checkbox]')
    .prop('checked', false)
    .trigger('change.crc');
```
