### ISSUE TITLE
Bower Support

### ISSUE THREAD

**Issue by mischah** [dciccale/Custom-radio-checkbox#12]
Could you add a `bower.json` and tag your releases according to [Semantic Versioning](http://semver-ftw.org/)?

See http://bower.io/docs/creating-packages

I could do the work for you in case you’re accepting a pull request for that :octocat:

**Comment by dciccale** [comment]
Done

**Comment by mischah** [comment]
Partly :wink: 
You need a tag according to the `version` property within the `bower.json`

Bower relies on Git Tags.
That’s the most important difference between Bower and npm.
Therefore you can publish a new version to bower by bumping the version within `bower.json` and pushing the update including the new tag to GitHub.

There’s no need to republish your package via the Bower cli.

**Comment by mischah** [comment]
https://github.com/dciccale/Custom-radio-checkbox/releases :kissing_heart:

**Comment by dciccale** [comment]
Done.

**Comment by mischah** [comment]
Thanks :+1:
