### ISSUE TITLE
Checkbox is only able to be clicked if it's inside the label tag

### ISSUE THREAD

**Issue by FiZiX** [dciccale/Custom-radio-checkbox#2]
I noticed that the checkbox element can only be clicked if it's inside the label tag. If it is outside the label tag, only the label can be clicked to change the status of the checkbox. For example:

<pre>
&lt;form&gt;
    &lt;input type=&quot;checkbox&quot; name=&quot;Checkbox&quot; id=&quot;checkbox1&quot; value=&quot;1&quot; /&gt;
    &lt;label for=&quot;checkbox1&quot;&gt;This checkbox won't be clickable&lt;/label&gt;
&lt;/form&gt;
</pre>

<pre>
&lt;form&gt;
    &lt;label for=&quot;checkbox1&quot;&gt;
        &lt;input type=&quot;checkbox&quot; name=&quot;Checkbox&quot; id=&quot;checkbox1&quot; value=&quot;1&quot; /&gt;This one will be clickable!
    &lt;/label&gt;
&lt;/form&gt;
</pre>

I believe the W3C would prefer that input elements are outside of label tags:

http://www.w3.org/TR/html4/interact/forms.html

**Comment by dciccale** [comment]
The specification shows than can be written in both ways (http://www.w3.org/TR/html4/interact/forms.html#edef-LABEL). If the for attribute is missing, you can put the input inside the label so that the label controls than input. But Internet Explorer does not fires the native change event without the for attribute so my example is written with the for attribute plus the input inside the label.

**Comment by dciccale** [comment]
I have tested the script and it works fine with the html written both ways. I will add an example.

**Comment by FiZiX** [comment]
Actually your demo has confirmed the issue. When the checkbox is outside the label tag, the checkbox itself cannot be clicked to change the status of the checkbox. The label can still be clicked to change the status, but the checkbox itself cannot. This could be confusing to some users because, before your script takes effect, the only way to change the status of the checkbox is to click on it (not the label).

**Comment by FiZiX** [comment]
Here's another example of why this could be a problem:

<pre>
&lt;p&gt;
    &lt;input type=&quot;checkbox&quot; name=&quot;Checkbox&quot; id=&quot;checkbox1&quot; value=&quot;1&quot; /&gt;Checkbox 1
&lt;/p&gt;
&lt;p&gt;
    &lt;input type=&quot;checkbox&quot; name=&quot;Checkbox&quot; id=&quot;checkbox2&quot; value=&quot;2&quot; /&gt;Checkbox 2
&lt;/p&gt;
&lt;p&gt;
    &lt;input type=&quot;checkbox&quot; name=&quot;Checkbox&quot; id=&quot;checkbox3&quot; value=&quot;3&quot; /&gt;Checkbox 3
&lt;/p&gt;
</pre>


Although this wouldn't pass W3C validation, checkboxes are often used and work without any label tag. Once your script is run, the checkboxes will become unusable.

**Comment by dciccale** [comment]
You are right, i will add support for clicking the custom radio/checkbox itself.

But i won't give support for bad written HTML, at least for now.

Thank you for the observations.

**Comment by dciccale** [comment]
Now it supports clicking the fake input to trigger the change event, only if the input is outside the label. If not i let the browser native change event do the job of checking/unchecking.

**Comment by FiZiX** [comment]
Looks great now. Thanks!
