### ISSUE TITLE
Widget not active

### ISSUE THREAD

**Issue by ghost** [dciccale/Custom-radio-checkbox#3]
Hello:

The fake radio and checkboxes are not themselves active: you can only click on the label to set them.

Here is a diff to activate them:

57a58,62

> ```
>       // make fake input active 
>               $(this).prev().click(function () {
>               $(this).next().click();
>               });
> ```
> 
> 80a86,90
> 
> ```
>       // make fake input active 
>               $(this).prev().click(function () {
>               $(this).next().click();
>               });
> ```

**Comment by ghost** [comment]
Actually, this seems better:

change the first
$(this).next().click();

for 
$(this).next().trigger("change.styledRadio");

and the second
$(this).next().click();

for
$(this).next().trigger("change.styledCheckbox");

in my diff above (sorry the pasting of a diff in replies seems to be broken).

**Comment by dciccale** [comment]
The problem is that the function change.styledCheckbox/Radio does not checks or unchecks the input, i am letting that up to the browser. So doing what you are proposing only will "check" the image but not the input itself.

I will work on a solution in the next days, or if you came up with one is good too!

**Comment by dciccale** [comment]
Now it supports clicking the fake input to trigger the change event, only if the input is outside the label. If not i let the browser native change event do the job of checking/unchecking.

**Comment by ghost** [comment]
Good work!

**Comment by dciccale** [comment]
Thanks man!
