### ISSUE TITLE
Request: Ability to only change checkboxes or only radio buttons

### ISSUE THREAD

**Issue by FiZiX** [dciccale/Custom-radio-checkbox#5]
Would it be possible to add an option to only change checkboxes or only change radio buttons? I'm trying to use the jquery UI buttonset() on my radio buttons and customRadioCheckbox() is interfering.

**Comment by dciccale** [comment]
Hello @FiZiX i will think of a fix for that, for now you can use a workaround, for example after you execute the buttonset(), do this in your code:

``` javascript
$(".ui-buttonset").find("input[type=checkbox]").unbind("change.crc").removeClass("hideInput").next().remove();
```

this way you remove the event and image of the Custom Radio Checkbox

*remember doing this after applying the buttonset
